# Generated by Django 4.2.30 on 2026-09-22 07:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks_management", "0010_add_search_all_perms_admin"),
        ("deduplication", "0001_add_beneficiary_deduplication_right_to_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanState",
            fields=[
                (
                    "kind",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_id", models.CharField(blank=True, default="", max_length=64)),
                ("last_scan_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "deduplication_scan_state",
            },
        ),
        migrations.CreateModel(
            name="DuplicateCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_model", models.CharField(max_length=255)),
                ("subject_a", models.CharField(max_length=64)),
                ("subject_b", models.CharField(max_length=64)),
                ("kind", models.CharField(max_length=32)),
                ("source", models.CharField(max_length=64)),
                ("score", models.FloatField(blank=True, null=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CONFIRMED", "Confirmed"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                (
                    "reviewed_by",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True, default="")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="duplicate_candidates",
                        to="tasks_management.task",
                    ),
                ),
            ],
            options={
                "db_table": "deduplication_candidate",
                "indexes": [
                    models.Index(
                        fields=["status", "kind"], name="dedup_candidate_status_kind"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="duplicatecandidate",
            constraint=models.UniqueConstraint(
                fields=("subject_model", "subject_a", "subject_b", "kind"),
                name="dedup_candidate_unique_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="duplicatecandidate",
            constraint=models.CheckConstraint(
                check=models.Q(("subject_a__lt", models.F("subject_b"))),
                name="dedup_candidate_subject_order",
            ),
        ),
    ]
